# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-11 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('userpassword', models.CharField(max_length=40)),
                ('useremal', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
