# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phonenum',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='youbian',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
